# Matrices
- A matrix can be defined as a rectangular array of numbers. They can be measured by m rows and n columns = m*n. If a matrix has the same number of rows and columns, it is called square.
- The transpose of a matrix is obtained by interchanging the rows and columns of the original matrix. For example:

In [11]:
import numpy as np

# Create a 2x4 matrix
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

# Display the matrix
matrix


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Which then becomes:

In [12]:
import numpy as np

# Create a 2x4 matrix
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

# Transpose the matrix
transposed_matrix = matrix.T  # or np.transpose(matrix)

# Display the transposed matrix
transposed_matrix


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Below are five examples of matrices:

# Question 1:

In [1]:
import numpy as np

# Matrix A
print("Matrix A:")
matrix = np.array([
    [6, 2, 3],
    [4, 3, 6],
    [3, 8, 9],
    [10, 2, 12]
])

matrix


Matrix A:


array([[ 6,  2,  3],
       [ 4,  3,  6],
       [ 3,  8,  9],
       [10,  2, 12]])

A) What size is matrix A?  
B) What is the third column of matrix A?  
C) What is the second row of matrix A?  
D) What is the element of matrix A in the 
(2,2) position?  
E) What is the transpose of matrix A (A')?

Answers:  
A) 4x3  
B) 3, 6, 9, 12  
C) 4, 3, 6  
D) 3  
E)  
[6, 4, 3, 10]  
[2, 3, 8, 2]  
[3, 6, 9, 12]

# Question 2:
Find A + B, where

In [28]:
import numpy as np

# Matrix A
A = np.array([
    [1, -3, 5],
    [4, 8, -6],
    [-2, 8, 9]
])

# Matrix B
B = np.array([
    [2, 4, -6],
    [-1, 10, -8],
    [7, -3, 5]
])

# Display the matrices
A, B


(array([[ 1, -3,  5],
        [ 4,  8, -6],
        [-2,  8,  9]]),
 array([[ 2,  4, -6],
        [-1, 10, -8],
        [ 7, -3,  5]]))

Answer:

In [36]:
import numpy as np

# Matrix A
A = np.array([
    [1, -3, 5],
    [4, 8, -6],
    [-2, 8, 9]
])

# Matrix B
B = np.array([
    [2, 4, -6],
    [-1, 10, -8],
    [7, -3, 5]
])

# Adding matrices A and B
result = A + B

# Displaying the result
result

array([[  3,   1,  -1],
       [  3,  18, -14],
       [  5,   5,  14]])

# Question 3
Find the product AB, where

In [29]:
import numpy as np

# Matrix A
A = np.array([
    [1, -3, 5],
    [4, 8, -6],
    [-2, 8, 9]
])

# Matrix B
B = np.array([
    [2, 4, -6],
    [-1, 10, -8],
    [7, -3, 5]
])

# Display the matrices
A, B

(array([[ 1, -3,  5],
        [ 4,  8, -6],
        [-2,  8,  9]]),
 array([[ 2,  4, -6],
        [-1, 10, -8],
        [ 7, -3,  5]]))

Answer:

In [37]:
import numpy as np

# Matrix A
A = np.array([
    [1, -3, 5],
    [4, 8, -6],
    [-2, 8, 9]
])

# Matrix B
B = np.array([
    [2, 4, -6],
    [-1, 10, -8],
    [7, -3, 5]
])

# Finding the product of matrices A and B
product = np.dot(A, B)  # or simply A @ B

# Displaying the result
product

array([[  40,  -41,   43],
       [ -42,  114, -118],
       [  51,   45,   -7]])

# Question 4
Let

In [34]:
import numpy as np

# Matrix a
a = np.array([
    [0, 0],
    [1, 0]
])

# Matrix b
b = np.array([
    [1, 0],
    [0, 1]
])

# Display the matrices
a, b

(array([[0, 0],
        [1, 0]]),
 array([[1, 0],
        [0, 1]]))

Find  
a) $$A \vee B$$  
b) $$A \land B$$   
c) $$A \odot B$$

Answer:

In [9]:
import numpy as np

# Creating Matrix a (2x2) with ones
matrix_a = np.ones((2, 2))

# Creating Matrix b (2x2) with specific values
matrix_b = np.array([[0, 0],
                    [1, 0]])

# Creating Matrix c (2x2) with specific values
matrix_c = np.array([[1, 1],
                    [1, 0]])

# Displaying Matrix a
print("Matrix a:")
print(matrix_a)

# Displaying Matrix b
print("\nMatrix b:")
print(matrix_b)

# Displaying Matrix c
print("\nMatrix c:")
print(matrix_c)


Matrix a:
[[1. 1.]
 [1. 1.]]

Matrix b:
[[0 0]
 [1 0]]

Matrix c:
[[1 1]
 [1 0]]


# Question 5

Let A be a zero-one matrix. Show that  
a) A v A = A  
b) A ^ A = A

Answer:

a) $$A \vee A=[a_{ij} \vee \, a_{ij}] = [a_{ij}] = A$$  
b) $$A \land A=[a_{ij} \land \, a_{ij}] = [a_{ij}] = A$$  

# Here are three code examples of matrices:

In [3]:
import numpy as np

# Creating a 3x3 identity matrix
identity_matrix = np.eye(3)

# Displaying the identity matrix
print("Identity Matrix:")
print(identity_matrix)

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np

# Creating a 4x2 matrix with random values between 0 and 1
random_matrix = np.random.rand(4, 2)

# Displaying the random matrix
print("Random Matrix:")
print(random_matrix)

Random Matrix:
[[0.00907622 0.51454163]
 [0.3893526  0.51179779]
 [0.90934872 0.29838057]
 [0.71614014 0.38973795]]


In [4]:
import numpy as np

# Creating a 3x3 diagonal matrix with specified diagonal values
diagonal_matrix = np.diag([2, 4, 6])

# Displaying the diagonal matrix
print("Diagonal Matrix:")
print(diagonal_matrix)

Diagonal Matrix:
[[2 0 0]
 [0 4 0]
 [0 0 6]]
