# Matrices Practice Solutions

Worked solutions for the practice problems in [`05_matrices.ipynb`](../05_matrices.ipynb).

### Problem 1: Matrix Addition

Using NumPy, compute $A + B$ for the matrices defined in the starter.

In [1]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)


[[ 6  8]
 [10 12]]


### Problem 2: Matrix Multiplication

Compute the matrix product $A B$ (use the `@` operator). Is $AB$ equal to $BA$?

In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A @ B =\n", A @ B)
print("B @ A =\n", B @ A)
print("AB == BA ?", np.array_equal(A @ B, B @ A))   # False: matrix multiplication is not commutative


A @ B =
 [[19 22]
 [43 50]]
B @ A =
 [[23 34]
 [31 46]]
AB == BA ? False


### Problem 3: Transpose

Print the transpose $A^{T}$ of the matrix $A$.

In [3]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])

print(A.T)


[[1 4]
 [2 5]
 [3 6]]


### Problem 4: Scalar Multiplication and the Identity

Compute $3A$, and print the $3 \times 3$ identity matrix.

In [4]:
import numpy as np
A = np.array([[1, 2], [3, 4]])

print("3A =\n", 3 * A)
print("3x3 identity =\n", np.eye(3, dtype=int))


3A =
 [[ 3  6]
 [ 9 12]]
3x3 identity =
 [[1 0 0]
 [0 1 0]
 [0 0 1]]
